{% set name = "tangods-achtung" %}
{% set version = "0.11.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tangods_achtung-{{ version }}.tar.gz
  sha256: 4a82151fb955be810ec218024d408d687aca807ba97c8468454d84e3c351155c

build:
  entry_points:
    - Achtung = achtung.achtung:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=45
    - wheel
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.9
    - pytango
    - pyparsing
    - httpx

test:
  imports:
    - achtung
  commands:
    - pip check
    - Achtung --help
  requires:
    - pip

about:
  home: https://gitlab.com/MaxIV/dev-maxiv-achtung
  summary: Achtung, a Tango device for managing alarms (Panic compatible)
  license: GPL-3.0-or-later
  license_file: LICENSE.txt
  dev_url: https://gitlab.com/MaxIV/dev-maxiv-achtung

extra:
  recipe-maintainers:
    - beenje
    - johanfforsberg
