schema_version: 1

context:
  name: tangods-achtung
  version: 0.13.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/tangods_achtung-${{ version }}.tar.gz
  sha256: 14821362d3ba544d974a4440add5c81d687c725ab19da39fd1f88c915a5958f4

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - Achtung = achtung.achtung:main

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=45
    - wheel
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=${{ python_min }}
    - pytango
    - pyparsing
    - httpx

tests:
  - python:
      imports:
        - achtung
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check
      - Achtung --help

about:
  summary: Achtung, a Tango device for managing alarms (Panic compatible)
  license: GPL-3.0-or-later
  license_file: LICENSE.txt
  homepage: https://gitlab.com/MaxIV/dev-maxiv-achtung
  repository: https://gitlab.com/MaxIV/dev-maxiv-achtung

extra:
  recipe-maintainers:
    - beenje
    - johanfforsberg
